### ISSUE TITLE
ui: show recently matched orders

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1143]
Would be nice to be able to see a list of the recently matched orders like they have on Binance.

**Comment by chappjc** [comment]
We should discuss design.  Since there's no server request for match history, this can only come from the client's local book subscription.  This would have to be combined with information from the `match_proof` notification.

In `(*EpochQueue).GenerateMatchProof` we identify the order IDs that were matched in the epoch, and the sorting seed used to prime the actual order matching.  However, the matching is not replicated client-side.  The shuffle would need to be applied and the matcher run (assuming client's local order book was synced and had all the orders in that epoch).

This SHOULD be doable, but I'd like to get a completely plan because it's not super clear how best to do it.

Supplementing the match proof ntfn with all the match details might be ok too.

**Comment by chappjc** [comment]
> I think adding a `[]BasicMatch` into `MatchProofNote` would be a simple solution, and as it would be only with the recent matches, I think it would be okay to have all this params into its struct. I also believe we can add a `Timestamp` field into `BasicMatch` and with that it would be very simple to show this information into the client.

Since all the matches in an epoch are matched with the same timestamp, the `Epoch` field of `MatchProofNote` provides the timestamp (subscriber should also know the epoch duration).
