### ISSUE TITLE
Setup relayer to submit ETH redemption transactions

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1195]
From matrix: 

Regarding the UX issue of a user with no ETH trying to buy ETH, it would be nice to setup a relayer that would submit the transaction on behalf of a user, and would receive the funds required for the gas fee + a little convenience fee. It wouldn’t be a requirement to use this, just optional if you don’t have any ETH.

It actually wouldn’t be too much work to do this: https://docs.openzeppelin.com/defender/relay

We would be sending meta-transactions. they already have the solidity contract that the swap contract would have to depend on, and the infrastructure to hold the private keys and send the transactions

**Comment by chappjc** [comment]
It's a UX issue that needs to be solved somehow, but it sounds like this introduces a trusted third party, and it would be configured and administered by dex devs?
I admittedly don't understand this well, but it would likely turn us or whoever puts up the eth to fund the execution of those transactions into money transmitters.  And there's a service that actively signs these txns for us.  Is that how it works?

I can see this working as an option where the user specifies a relayer they want to use instead of their own account as a destination for the swap, but I don't think that relayer could be something configured or administered by Decred.

**Comment by JoeGruffins** [comment]
Just my opinion, but while this is a problem, just swaps working and being secure comes first. Also, there is work to get contracts to pay gas which would also solve our problem, as we could take gas from the value as we do with utxo coins, but there's no telling when that may or may not happen.

**Comment by buck54321** [comment]
I think there are definitely centralized, trusted services that can inserted between the user and the DEX that could smooth out some of the UX pain points. I could easily see a third-party service that can 

1) handle part or all of settlement on the clients behalf
2) provide order batching, enabling arbitrary trade sizes
3) provide liquidity for Lightning

I don't believe these are under the purview of dcrdex as a project. That's not to say we wouldn't accommodate such efforts, but its outside of our approved work plan and we wouldn't compensate for the work (without additional stakeholder approval).

Personally speaking, I would love to work on something like this soon though.

**Comment by martonp** [comment]
Yeah things like this would bring more users who want some more convenience, and it would also be good for users who want to avoid any centralized services because it would bring more liquidity.
