### ISSUE TITLE
btc spv: don't use hard-coded wallet birthday unless restoring

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1270]
A lot of the initial wallet sync is spent doing "restoration" = requesting and scanning filters from the hard-coded `walletBirthday`. But if the seed is being freshly generated, we don't need to restore. **core** will need to inform the wallet whether it is restoring from seed so that we can set the birthday appropriately.

We also don't know at wallet creation time whether the app seed was restored or created fresh. We'll need to persist that information in the client database app bucket.

**Comment by chappjc** [comment]
It's a good plan.

I also suggested a checked-by-default "Fresh wallet, do not rescan" kind of option for the native wallet creation dialog for a good UX. My primary concern getting that initial onboarding for green users to be smooth.
But if the solution in this issue (recording if fresh app seed or not in the DB) make a checkbox unneeded, that's good too.  Even with this automatic solution, I can still see a need for either the checkbox or a manual birthday entry because the user may know the wallet is never used, or may know the first time they used it.

**Comment by martonp** [comment]
I can do this.

**Comment by chappjc** [comment]
Sounds good @martonp.  Would you mind first detailing here which specific changes you'll pursue?  There's:
- the idea of fresh seed generation that will provide an earliest birthday time
- wallet creation UI change to use current time as birthday
- wallet creation UI change to specify a birthday date-time
- when restoring from seed, entering an optional previous creation date-time

If restoring from seed as we do now (without any user-provided birthday), at least come of the above UI changes would be needed otherwise only the one installation that generated the seed would benefit from the recorded birthday info.
Also the wallet creation UI changes could be helpful if the user knows they have never created or used the wallet, even if the app seed generation date was recorded (and was potentially much longer ago).

Part of me wants just UI changes, but the DB update on init does have its merits.

**Comment by martonp** [comment]
I'll go for the first three options. I like the DB update because we'll be able to set a better default option on the wallet creation UI and avoid user error. For example if this is a fresh app, the default option will be to treat the wallet as fresh, but otherwise the default option will be to rescan from the hard-coded `walletBirthday`.

**Comment by martonp** [comment]
A prerequisite for the UI changes are the wallet traits that you have in #1375.

**Comment by chappjc** [comment]
Ok will wrap that up.  I don't think we can make traits solely based on method availability though, the main example being the `Rescan` method that is only functional for SPV, and a no-op for RCP.  It could work for RPC, but the point is a given `ExchangeWallet` has variable functionality depending on the `WalletType`, and the the only way to rely on method signatures to infer traits is to give each different wallet type a different concrete type e.g. ExchangeWalletSPV

**Comment by martonp** [comment]
Another example is also the single address trait which also cannot be done based on method availability.

**Comment by chappjc** [comment]
> Another example is also the single address trait which also cannot be done based on method availability.

@buck54321 did have a suggestion for that, which worked, but in general I don't see that scaling too well, with more-or-less dummy methods.  I'm not 100% opposed to that approach, but I get hesitant when it seems like we're creating hoops to jump though.

Anyway, I will wrap up #1375 and we'll have another look.

**Comment by chappjc** [comment]
@martonp See if it's possible to use the traits defined based on methods as in the updated #1375, if not, we can switch back to just explicitly listing the traits out per-wallet-type.

**Comment by martonp** [comment]
I think that will work well.
