### ISSUE TITLE
eth: Manual refunds

### ISSUE THREAD

**Issue by martonp** [decred/dcrdex#1311]
For BTC and DCR, we log a signed refund transaction that the user can manually submit to the blockchain in case the dex fails to properly refund a swap. For ETH this is not possible, because the nonce might have been incremented by the time the user would need to do a refund. We need an different way to do manual refunds for ETH.

**Comment by chappjc** [comment]
In the past I had made a couple quick and dirty tools to do refunds and redeems without dexc.

https://github.com/decred/dcrdex/commit/cb15c2fefe2eb44a24060fd196fc9e86a4214046

- The `redeem` tool works like `redeem <txid> <vout> <contract script> <secret>`, but it can be made to work like `redeem <raw tx hex> <contract script> <secret>`.  This tool is useful if you are the taker, and the maker has redeemed your contract, but your dexc is disabled before you can redeem theirs.  With logged data, you can do the redeem manually.
- The `refundall` tool is a bit different in that it chugs through the dexc.log file and attempts to refund any unspent contract that was logged.  Instead of scanning the log file, a new `refund` tool can be made to work like `redeem` by processing a specified contract of your own.

These are not well generalized at all currently, only working with DCR and BTC, but that can change.

**Comment by martonp** [comment]
Those look nice.. I was thinking about something similar to the `refund` tool that you mentioned where you specify a contract of your own, but it would definitely be more convenient to have something that just scans the log files.

With ETH they are already deterministic as long as we only use a single swap contract. Definitely would be harder with DCR/BTC. I guess we would need the wallet to keep track of all the unredeemed swaps in the UTXO set.

**Comment by chappjc** [comment]
> With ETH they are already deterministic as long as we only use a single swap contract

Address reuse and the central contract with ETH certainly makes things easier, even if crazier.

A complementary idea that @buck54321 had suggested was a secondary record of the essential swap data, which would be redundant with both the DB and the log file, but potentially provide a more concise and easily parseable record of the critical on-chain swap data.

- another file such as "critical.txt", synchronous and flushed after each write
- match ID on each line to link all logged data
- more structured than the .log file so that it is easily machine readable
- any data that would be required to perform refund or taker redeems such as contract scripts, transaction IDs, counter party secrets

It's all already in the log file as I've demonstrated, but this would still be valuable IMO.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/1455, which permits manual refunds to be performed.  The refund of course still pays to the initiator's account, which would be the dex ETH wallet, so actually claiming those funds requires the app or asset seed, but it can at least be done without the dexc.db.
