### ISSUE TITLE
Need a password-based key encryption scheme for the client

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#151]
As it stands, each DEX account has its own private key. The key is stored unencrypted, which is obviously nonsense.  

1. Does each DEX need its own key, or should there be a single app-wide key?
2. Do we need to generate a mnemonic seed so that accounts can be recovered?
3. dcrwallet's [snacl](https://github.com/decred/dcrwallet/tree/master/wallet/internal/snacl) was my first instinct, but @jrick has expressed some reservations about it, providing a possible path forward, though.

> secretbox is still pretty good, but i would like to replace scrypt with argon2id

I will note that I don't fully understand the objection to scrypt or the snacl implementation in general, but if there are better options, it's certainly worth consideration.

Luckily, this is an implementation detail that doesn't require any consideration for future alternative clients.

**Comment by jrick** [comment]
You want argon2id for turning passphrases into keys, and chacha20poly1305 to encrypt any other data.  Use the key from argon2id as the chacha20poly1305 key.

Use xchacha20poly1305 instead of chacha20poly1305 if you are reusing the key with random (instead of incrementing) nonces.

**Comment by chappjc** [comment]
Two links from jrick on Matrix chat, so I can clean up by browser tabs:
- https://gist.github.com/jrick/8000897335b6315926ebbe9d3edd07fc
- https://github.com/jrick/ss/blob/master/keyfile/keyfile.go

**Comment by jrick** [comment]
You should also not reuse an encryption key for other pursoses.  For example, if you were wanting to protect e.g. ed25519 signing keys, these keys should be derived separately from the passphrase using just cryptographic randomness.  These keys could then be encrypted using (x)chacha20poly1305 with a symmetric encryption key being derived from the user's provided passphrase.

You might also want to be able to change passphrases.  The most efficient way to do this is to use an inner and an outer encryption key.  The bulk of the data (e.g. your protocol signing keys) should be encrypted by the inner key, and the inner key itself being encrypted by an outer key.  Changing the passphrase then involves only reencrypting the inner key using a new derived outer key, rather than reencrypting encrypted data.
