### ISSUE TITLE
When order is manually canceled, the "Filled" field becomes 100%

### ISSUE THREAD

**Issue by xsanchezz** [decred/dcrdex#1608]
Should not be 0%?

<img width="543" alt="Screen Shot 2022-05-07 at 4 27 56 PM" src="https://user-images.githubusercontent.com/4775731/167270756-7372ea4e-0dab-4864-a5d0-722240864285.png">

**Comment by xsanchezz** [comment]
Okay, I got another question:

After placing an order and partially filled, I see that I have now 184 million Bitcoins available?

<img width="555" alt="Screen Shot 2022-05-07 at 4 34 16 PM" src="https://user-images.githubusercontent.com/4775731/167270917-d09fc52c-75a6-46be-86a6-4d511016e8ef.png">

**Comment by chappjc** [comment]
> After placing an order and partially filled, I see that I have now 184 million Bitcoins available?

https://github.com/decred/dcrdex/issues/1491

Pretty sure that was resolved in 0.4.2
Can you confirm the version you're running?

**Comment by xsanchezz** [comment]
Well, I am using the version that comes with Decrediton 1.7.1

DEX Build ID: 8ffa2e3

**Comment by chappjc** [comment]
> Well, I am using the version that comes with Decrediton 1.7.1
> 
> DEX Build ID: [8ffa2e3](https://github.com/decred/dcrdex/commit/8ffa2e39f473a13f63b4f15670c17e12bad2b80d)

Yup, that's the commit of v0.4.1.  I believe a Decrediton patch release is being prepared with v0.4.3 
That's planned, right @alexlyp ?

**Comment by ukane-philemon** [comment]
> Should not be 0%?
> 
> <img alt="Screen Shot 2022-05-07 at 4 27 56 PM" width="543" src="https://user-images.githubusercontent.com/4775731/167270756-7372ea4e-0dab-4864-a5d0-722240864285.png">

@chappjc, Considering that an order can be cancelled by a cancel order  of type `(*order.CancelOrder)` that is eventually linked to the original order via `(*db.MetaOrder).MetaData.LinkedOrder`,  what order information should be displayed on the `order/orderid..` and `order` page? information for linked cancel order of type `(*order.CancelOrder)` if any or the original order?

Cancel order of type `(*order.CancelOrder)` lacks some information related to the original order, like `Rate`, `Quantity`, `FundingCoins`. etc..

**Comment by chappjc** [comment]
What is displayed on the order page now looks right (except the filled amount).  Namely, it shows trade matches and any match with a cancel order:

![image](https://user-images.githubusercontent.com/9373513/177642301-4bfa4408-2abe-48c6-b32b-d3c4ed12c712.png)

That red "Cancellation" match is sufficient I think.  There's no need to show info about a "cancel order" that did that.  Most users don't need to know that there is a special "cancel order" just that their request to cancel the trade order was executed. 

All that is required to resolves this issue is to have frontend display the portion of the filled amount that is from trade matches, not a cancel match.  This corresponds to the `matchFilled` quantity from `(*trackedTrade)recalcFilled`:

https://github.com/decred/dcrdex/blob/1961b68a38a4c886f9708166f7b64eff438a2f30/client/core/trade.go#L736

If that can be done entirely without backend changes, that's best.
