### ISSUE TITLE
server: SetOrderCompleteTime unable to set completed time error.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1697]
I'm not sure how to reproduce this with just the harness, but I see it every time I use the loadbot on dcr_eth. Start loadbot then turn it off and wait a bit.

The error:
```
2022-07-06 16:23:59.014 [ERR] MKT: SetOrderCompleteTime for 885a5d2c3eae30bc7e718a0b643a5bdfc7bf60f6b288a38907c103cc6a20cd22: order not in executed status: unable to set completed time for order 885a5d2c3eae30bc7e718a0b643a5bdfc7bf60f6b288a38907c103cc6a20cd22 not in executed status 
```

server logs:
[dcrdex.txt](https://github.com/decred/dcrdex/files/9052608/dcrdex.txt)

**Comment by chappjc** [comment]
Circumstances: user has a booked order with an active swap, user goes MIA and server unbooks (revokes) orders, active swap eventually revokes with *other* user at fault, swapDone called with fault=false since the user didn't technically break the swap, `SetOrderCompleteTime` called to give order completion credit to the user.

Fix: make revoked orders handled like canceled orders by removing the entry from the `settling` map that is to ultimately assign completion credit on final swap completion.

Consequence of bug: in rare circumstances a user can get order completion credit for a revoked order if an active swap for that order completes or does not fail with them at fault.
