### ISSUE TITLE
decide if match_proof and preimage messages need signatures

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#170]
_Originally posted by @buck54321 in https://github.com/decred/dcrdex/pull/145#discussion_r373778261

**Comment by dnldd** [comment]
considering how heavy `match_proof` payloads can get I think it makes sense to have them signed, would be better for the payload to fail at the signature verification than to generate match proofs and fail there I think.

**Comment by chappjc** [comment]
I wasn't thinking about this from a wire data integrity point of view, but rather for proof of a server's actions.  When you say "better ... than to generate match proofs and fail there" do you mean JSON unmarshal errors or the client-side seed and csum validation?  In the single server - client setup, I expect that the server would still provide a valid signature even if they decided to send data that failed epoch validation.

**Comment by dnldd** [comment]
I'm referring to client side seed csum validation, I'm thinking since the match-proof payload size is variable and currently without a signature it could be an ideal target to DOS a match proof verifying client. That's why I'm thinking it'd be better in that scenario to fail at signature verification than at the match proof generation.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?
