### ISSUE TITLE
server/eth: Add a "consensus layer client" to the simnet harness.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1788]
Look under `Non-validating node operators and infrastructure providers` at https://ethereum.org/en/upgrades/merge/

I guess we would use "prysm"? https://docs.prylabs.network/docs/prepare-for-merge

It seems this is necessary for the latest geth release `v1.10.21`

We probably need to have a wiki page for geth server setup as well.

**Comment by JoeGruffins** [comment]
I can do this.

**Comment by chappjc** [comment]
Related question.  For the ability to put geth on a different host from dcrdex, we'd probably need to use http API anyway (instead of IPC).  The [Prysm setup instructions](https://docs.prylabs.network/docs/install/install-with-script) describe setting up geth for execution and Prysm for consensus, where Prysm connects to geth via the HTTP api (`geth --http --http.api eth,net,engine,admin)`.  We should look at allowing dcrdex to communicate with geth that way too.  Probably a bigger issue now if 2TB are needed for a mainnet full-node now.

**Comment by chappjc** [comment]
Oh, so why does https://github.com/decred/dcrdex/pull/1795 not require a consensus client?  Does the merge just never happen on dev network?

**Comment by buck54321** [comment]
> Oh, so why does #1795 not require a consensus client? Does the merge just never happen on dev network?

We decide when the merge happens on our own network. We'll just stay pow, since it's built into geth. On a cursory look, it seems like to switch to the new consensus engine, we would need a non-nil `catalystBlock` in our genesis config, and we're not setting that field in our harnesses.
