### ISSUE TITLE
client: config file errors should be sanitized

### ISSUE THREAD

**Issue by degeri** [decred/dcrdex#182]
```
/api/newwallet
```
has a parameter "inipath" any errors from this config read should be sanitized since it might expose contents of sensitive files. 

```

 curl 'http://127.0.0.1:5758/api/newwallet'  -H 'content-type: application/json'  --data '{"assetID":42,"pass":"","account":"","inipath":"/etc/passwd"}'


{"ok":false,"msg":"error creating dcr wallet: error loading wallet for 42 -\u003e dcr: error creating wallet: error parsing DCR ini file: /etc/passwd:1: malformed key=value (root:x:0:0:root:/root:/bin/bash)"}
```

**Comment by itswisdomagain** [comment]
Related https://github.com/decred/dcrdex/pull/352#discussion_r425849144

**Comment by ukane-philemon** [comment]
When parsing a config file, error as a result of unexpected key in config file does include the malformed key.

It's a good thing, in that it can help user see what's wrong with the config file and fix it.

And this 
> expose contents of sensitive files.

Experienced this recently, while parsing a non-config file. 

Possible ways around this-
1. Let user know there's something wrong with their config file on line xx instead of the incorrect token which might be a sensitive information.
2. Keep as is, that's let user see malformed key. Helps with debugging.

**Comment by chappjc** [comment]
Most of the api endpoints require auth now, so I'm not sure if it's still a big issue.

**Comment by chappjc** [comment]
```
$  curl 'http://127.0.0.1:5758/api/newwallet'  -H 'content-type: application/json'  --data '{"assetID":42,"pass":"","account":"","inipath":"/etc/passwd"}'
not authorized - login first
```

**Comment by ukane-philemon** [comment]
> Most of the api endpoints require auth now, so I'm not sure if it's still a big issue.

should be closed? there is no need to sanitize config file errors because they give details about malformed keys=values. And is obviously for authed users.

**Comment by chappjc** [comment]
What do you think @degeri?  Since these endpoints that parse files as the user owning the dexc process now require authorization, do we still need to hide the error details that may contain information about the contents of the file?  It would be unfortunate to lose the specific error if say there's a syntax error in the correct file because it would be hard to know what line to correct.

**Comment by chappjc** [comment]
For ref, the api endpoint auth issues were resolved in https://github.com/decred/dcrdex/pull/753 and https://github.com/decred/dcrdex/pull/918

**Comment by degeri** [comment]
if we have auth it should be ok.

**Comment by degeri** [comment]
Additionally  we can enforce "*.ini" to limit a non config file from being selected.

**Comment by chappjc** [comment]
Hmm, or a combination of .conf, .cfg, .cnf, .ini, etc. I suppose.  Could break someone's weird setup, but does make sense.
