### ISSUE TITLE
ui: hide advanced order options by default?

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1874]
There was some interest in hiding the advanced order options by default. I'm open to that. We would want to take care with the design and the messaging.

Just an option to consider. I'm find with leaving it too.

**Comment by chappjc** [comment]
I get hiding the fee bump sliders since most of the time they shouldn't be used, and they are even a touch misleading (Faster Swaps and Faster Redemption is not accurate if blocks have free space anyway, making it just a waste of funds).

On the other hand, of come to really like seeing the current selection for the txsplit. In fact, it really highlights that a default for that at order time might be to unselect it if the unlock savings is a tiny tiny fraction of lot size).

**Comment by vctt94** [comment]
Can work on that
