### ISSUE TITLE
Market order form inconsistencies

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#1920]
Similar issue to https://github.com/decred/dcrdex/issues/1908 for Market Buy Order.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/112318969/197753568-f0dc3b55-c1e2-401b-947d-d2eb60324de2.png">

And I'm kinda confused why Market Buy and Sell order forms are different
- for Buy DCR, I need to specify how much of my BTC I wanna exchange into DCR at most (that "at most" part isn't very clearly conveyed in UI btw); user doesn't have to adjust it manually, the adjustment will happen automatically
- for Sell DCR, I need to enter number of lots or DCR quantity adjusted to lot size

Is there a fundamental difference (when placing an order) between Market Buy/Sell ?
If not, can we make similar forms for both (and which one would be preferable - current version for Buy or current version for Sell)  ? I would be happy to try implementing this.

**Comment by buck54321** [comment]
All **matches** are in multiples of the lot size which is a fixed amount of the base asset. When **buying** (trading your quote asset for some base asset), if there is no price limit (as in a market order), there is no way to determine how many lots you will get, because the price is set at match time, and the book can look different by then.

On the other side, for market **sell** orders (trading our base asset for some quote asset), we can obviously size those into lots because we can size the order in units of base asset.

I **could** see a field where you enter a target number of lots and we approximate how much you should trade, but the messaging would need be just right so it was absolutely clear what was happening, because inevitably someone will ask for two lots, end up with one, and think "I only got half my order".

Market buy orders are strange. They require special handling all the way to the `Matcher`.

**Comment by norwnd** [comment]
Thank you for explanation,

**Two things put me off:**

1) Market Buy trade gets rounded to lot size, it's not clear with the current form used (the messaging can be improved, of course, and I believe it should)

2) when `Buy DCR` is chosen, I'm inputting BTC there (while on all other 3 forms - 2 with limit order, and market sell - I count my trade in DCR), and there doesn't seem to be a good (limiting) reason for that since I get a rough estimate for DCR I will receive anyway, and look mostly at this estimate when sizing my order; I think letting the user to input DCR and calculating rough amount of BTC to lock would provide a smoother UX, because

> because inevitably someone will ask for two lots, end up with one, and think "I only got half my order".

that's pretty much how I would describe my current attempt to do a market Buy DCR  order similar to this one (and getting it filled by only 1 lot, when there are 2 available on the market):

<img width="366" alt="image" src="https://user-images.githubusercontent.com/112318969/197872248-7922517c-8eef-4e5f-98c3-7e4a0dd706f3.png">

because I was "promised" to receive about 39 DCR, how come it's 20 ... :) Defi users are used to the concept of slippage, but with lot size of 20 that's on a whole another level (even though it's not actually "slippage" here, I realise that, it's the closest comparison I can make)

**my point is**: we have this rounding-to-lot-size issue regardless, better messaging  is the only improvement I can suggest for it right now, and flipping `Buy DCR` form to accept value in DCR doesn't really make it worse

**Comment by chappjc** [comment]
> 2\. when `Buy DCR` is chosen, I'm inputting BTC there (while on all other 3 forms - 2 with limit order, and market sell - I count my trade in DCR), and there doesn't seem to be a good (limiting) reason for that since I get a rough estimate for DCR I will receive anyway, and look mostly at this estimate when sizing my order; I think letting the user to input DCR and calculating rough amount of BTC to lock would provide a smoother UX, because

I think we should not be showing that "Receiving Approximately" value is all.  Or at least it should be rounded *down* to the nearest multiple of lot size.  As discussed by @buck54321 there are very good reasons not to try to specify a market buy in units of the base asset.

Plus, the messaging should be clearer that the estimate is based on the **current** sell orders on the book, and that they are likely to be different by the time the order is placed and matched.  I think it is folly to attempt to promise the user anything with market orders, and if we switched market buys to be denominated in the base asset, we'd be going even further in that direction.

> because I was "promised" to receive about 39 DCR, how come it's 20 ... :) Defi users are used to the concept of slippage, but with lot size of 20 that's on a whole another level (even though it's not actually "slippage" here, I realize that, it's the closest comparison I can make)

The 39 DCR estimate there is problematic, and not just because it is not a multiple of lot size, agreed. However, this is not reasonably close to "slippage" since it simply does not spend all of the BTC you committed to the order.  The rate doesn't slip to 20 DCR / 0.00039 BTC, it's that you only spend a portion of that 0.00039 BTC to get the 20 DCR.  You get 20 DCR and you keep the remaining BTC from the order that could not match with another sell order.  If you look at the order details page for such an order, the filled amount is less than 100% when it is fully executed and settled.

**Comment by buck54321** [comment]
Hey @norwnd. I love everything you're doing. Can you come chat with us at chat.decred.org in the DEX Development room?
