### ISSUE TITLE
UI/order details: invalid coin when finding eth redemption.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1927]
For eth based assets, when something happens that prevents one client from sending their redemption, and the other client finds the redemption, there is no txid. This is because the redemption is really a contract without any traceable connection to the redeeming tx (with our tools). This is fine. But when we show this nonexistent txid in the UI it does not look good.

![image](https://user-images.githubusercontent.com/34998433/198552794-4808562a-2577-4814-9637-2efe2ca7be76.png)

This is really this https://github.com/decred/dcrdex/blob/e4bdbf020465b7def3a9691dc9890b406f6d546e/client/asset/eth/eth.go#L150

Something more informative should be returned here. Or the UI should deal with it better. I don't know that there is anything we can point to on chain that makes sense in an explorer. If there is something we can point to that would be best.

Maybe just a message that reads something like "Redemption txid not accessible."?

**Comment by norwnd** [comment]
> I don't know that there is anything we can point to on chain that makes sense in an explorer. If there is something we can point to that would be best.

Googled about this a bit, it seems it isn't possible to pull out the actual smart-contract call transaction hash (which would be ideal), see
- the (closed) issue I've linked to above
- and current list of exposed variables:  https://docs.soliditylang.org/en/v0.8.17/cheatsheet.html#global-variables 

Note, `nonce` isn't exposed, that would not allow for `address` + `nonce` lookup  either (which would have been another option).

> "Redemption txid not accessible."?

That exact wording doesn't answer the "why" question, which is probably the most important one to answer,

maybe something like `"%s redeemed"` (where `%s` is counterparty's address) 
since `SwapState.Initiator` and `Swap.Participant` are already [exposed](https://github.com/decred/dcrdex/blob/d606490ca154807d5895acbcee9ee4a38d3c7b4f/dex/networks/eth/params.go#L207-L208) ?

**Comment by chappjc** [comment]
> maybe something like `"%s redeemed"` (where `%s` is counterparty's address)
> since `SwapState.Initiator` and `Swap.Participant` are already [exposed](https://github.com/decred/dcrdex/blob/d606490ca154807d5895acbcee9ee4a38d3c7b4f/dex/networks/eth/params.go#L207-L208), and that would allow for manual best-guess lookup at least ?

That seems reasonable to me. It would be `Initiator` always in our application since `FindRedemption` is run by the taker (participant).  I think `(*assetWallet) findSecret` could return the initiator's address in addition to the secret.  A special prefix would have to be added to the coin ID bytes so that `(*Driver) DecodeCoinID` can recognize it and decorate with whatever.  Only annoyance is it's more untranslated text...

**Comment by norwnd** [comment]
On it.
