### ISSUE TITLE
docs/wiki: Weird symbols.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2099]
I was looking at the readme at https://github.com/decred/dcrdex/wiki/Simnet-Testing#automatic-mining and some of the characters dont have symbols for my font, I guess. I also checked with an android phone on chrome and they were just boxes so it's probably not my fonts. There are probably more instances in the docs, but have not confirmed.

![image](https://user-images.githubusercontent.com/34998433/216284778-cb5c205c-ccfd-4f11-a370-0c286632b248.png)

**Comment by norwnd** [comment]
I've also noticed this recently (studying up on simnet testing), Goland IDE shows it like this for me:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/112318969/216975779-78058e24-b509-47f2-bc04-6da645f020a3.png">

which also means: those particular symbols you've used in https://github.com/decred/dcrdex/wiki/Simnet-Testing article are only present there(not in others).

I've sketched out PR that should adjust/remove those ^, but  maybe you'd want to change some settings ? so that it's compatible with Github and so on,
or alternatively look out [for this on review](https://github.com/decred/dcrdex/pull/1714/files) and adjust these manually:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/112318969/216978042-287e266a-9c90-4002-9a1b-ac9ac836b8ca.png">

**Comment by chappjc** [comment]
They are just symbols used by powerline to show a nice looking ">".  They used to look alright on a browser but now anymore.
