### ISSUE TITLE
eth: improve UX around token approvals

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#2331]
For convenience reasons, we have automatic token approval handled on the fly when submitting an order.  This leads to some surprises to the user.  Consider this message to a user trying to trade USDC, with 0.021996150 ETH in their wallet:

![image](https://user-images.githubusercontent.com/9373513/235240447-56090901-1dc7-4d3b-9ce6-c26d1048f83b.png)

That's confusing to all but the most technical users.  For example, in chat, we have to explain that this approval part of those fees only happens the first time, and it's a universal thing with ERC20s that you face even with Uniswap and not a DCRDEX issue.  Native ETH DEXes generally send the approval tx request to your wallet just before the swap begins, so they see a discrete approval tx signing prompt, but with DEX we make it automatic but it feels weird to the user.

A related issue is that we end up also explaining eip1559 dynamic transactions, and how they aren't likely to pay those fees unless the current gas price is close to the limit (which is ~180 gwei/gas but even that isn't conveyed clearly anywhere).  i.e. They almost certainly are not going to consume 0.04356 ETH on gas. Related shower thought: allow much smaller reserves and gas cap limit on the tx if the order is *immediate* time-in-force.

To improve this the approval issue:

- successfully creating a token wallet should be followed by a prompt to submit the approval transaction, with appropriate messaging about and/or links explaining
- the wallets page should include a conspicuous button or something for a use to do the approval on-demand

**Comment by buck54321** [comment]
I'm pretty sure UniSwap calls approve on token contracts every time you trade. It's not a terrible option, because we would be able to get swap estimates without having approval, something we've had to dance around. But it would raise the gas for every swap and cost substantially more in the long run, I think.

I'm not really sure what's best here. Our approval adds about a third to the reserved gas on a single-lot trade, and our swap estimation functions account for the extra gas. Ethereum users should also be accustomed with having higher gas costs the first time they interact with a contract. I'm wondering if this is something we could handle with messaging and maybe a section in our wiki to point to.

**Comment by chappjc** [comment]
A one time approval is the way to go here.  Doing a new approve on each trade is poor for the reasons you described.

It's quite common to do a one time approval for a variety of other dapps.  Let's see what others think, and really test the UniSwap assertion, but I think we have a real problem to fix personally.

**Comment by buck54321** [comment]
I may be wrong about UniSwap. I remember manually approving tokens, but I also see approval steps in their solidity code. Hmm.

**Comment by chappjc** [comment]
Yeah, just tried the Goerli/**testnet** app and it works like this the first time you swap *from* the token:

![image](https://user-images.githubusercontent.com/9373513/235251619-cfa71a18-1dc6-4c78-b23f-276b09aca947.png)

![image](https://user-images.githubusercontent.com/9373513/235251633-c8e0f017-2de8-48b0-a54c-22819e15cb3f.png)

![image](https://user-images.githubusercontent.com/9373513/235251647-e76c81c0-116b-4cf5-b58b-f9d901d2ec18.png)

![image](https://user-images.githubusercontent.com/9373513/235251659-da831920-639e-4c18-bac5-468c5fffc673.png)

(clicking "default" is the max value, so permanent basically)

It sends out the discrete approve transaction, and gets you to sign a message about approval too.

Then you go back to the swap form, but it says "Swap" then:

![image](https://user-images.githubusercontent.com/9373513/235252172-768705cb-4ce1-450f-be94-a2841acfffd9.png)

![image](https://user-images.githubusercontent.com/9373513/235252177-a734b870-be69-434d-8088-db6f14249074.png)

I completed the swap and went back again, and it was still ready to go, no additional approval:

![image](https://user-images.githubusercontent.com/9373513/235252243-ff6c4339-8fbd-4115-b33a-9e4ee6542657.png)

**Comment by chappjc** [comment]
I think maybe that signed message that was actually after the on-chain approval pertains to the bits of their Solidity code that pertains to approval too.

**Comment by martonp** [comment]
Best practice is to set some limit in the approval, but usually everyone just sets it to unlimited. We're already setting an unlimited approval, it's just happening automatically instead of as a separate step for the user.

I don't think a button is necessary, especially if we're not giving the option to set a limited amount for approval. I think if we have a popup when the user is placing their first USDC trade with a breakdown of exactly what is about to happen, it would suffice. Although I'm sure some super security conscious people wouldn't mind being able to set a smaller approval amount.

**Comment by chappjc** [comment]
> I think if we have a popup when the user is placing their first USDC trade with a breakdown of exactly what is about to happen, it would suffice. Although I'm sure some super security conscious people wouldn't mind being able to set a smaller approval amount.

I think the concern is not related to the approval amount, but rather the confusion of how much ETH is required for their first trade using the token and the subsequent error.  For this reason, a discrete approval confirmation (unlimited though) will greatly improve the UX because they will get it only once and it separates the funding requirements for the order from this.

**Comment by martonp** [comment]
The popup I was talking about would just appear once before you approve as well. The separate button sounds good too. There could be a button on the wallet page, and also one on the section where you place your order if the token has not yet been approved.

**Comment by martonp** [comment]
I'll fix this.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/2349.  Thanks @martonp
