### ISSUE TITLE
dexc account unrecoverable if account lost on dex server 

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#249]
2020-04-10 12:39:50.057 [ERR] WEB: login error: authorization errors: https://dex-test.ssgen.io:7232: 'connect' error: rpc error: 27: no account info found for account IDe3c000c2ae03fd58fda359bb9cbd8d4cdbc62064def8b016fe152d2fa5dcf6c4

<s>And dexc is stuck showing the app password prompt.</s> EDIT: apparently now the login works but the user cannot place orders being not authorized with the dex.  However, this is not much of an improvement because the user cannot re-register.

The only workaround for this is to delete dexc.db.  Ideally if the server does not recognize the account, dexc will clear that DEX server's account out of the client db and re-register.  Ideally the account entry would not actually be removed entirely, just flagged so it isn't used anymore, perhaps by prepending a "!" to the account id key or something similar.

**Comment by chappjc** [comment]
Assigned to @kevinstl

**Comment by kevinstl** [comment]
I think things may have changed since this issue was created.

I believe I've recreated the issue properly by changing account id in the dex accounts table. After changing dex account id I am still able to login, see the markets page and am not stuck at the login screen, though I am presented with: 

DEX auth error
22 m 18 s
ago
127.0.0.1:7232: 'connect' error: rpc error: 37: no account info found for account ID867bf65fe90....

in the notifications dialogue. Also I am unable to make orders.

I want to make sure I'm properly recreating the error. Note the error code 37 instead of 27 as it looks like the AuthenticationError change from 27 to 37.

There is still an issue here. The user is stuck and unable to fix the problem without deleting the client db and re-registering.

I plan to proceed with the fix as requested.

Instead of prepending ! to account id on the client db would it make sense to add a status column or utilize the accounts.active field to indicate the account was disabled due to non matching account id on dex side?

**Comment by chappjc** [comment]
I defer to the devs who have done the bulk of client db work to decide how to disable an account without deleting it entirely (for historical reasons).

But it is clear that there needs to be handling in the client for the `AuthenticationError` / `no account info found for account ...`.  Disabling the account seems like a good start.  With multiple DEXs (https://github.com/decred/dcrdex/pull/404) the resolution is probably not to automatically reregister, but perhaps initiate a registration dialog to make it clear if they didn't see the notification.  @song50119 Please comment on how you imagine handling this case given your work.  Hopefully it would not be necessary to restart dexc after the account is flagged as disabled / invalid after a failed auth.

Also, if it is server trouble (e.g. temporary DB failure), it would be valuable to somehow re-enable such accounts in the event that the server DB is restored and the original account becomes valid once again.

**Comment by kevinstl** [comment]
Adding here to spell out how I've changed it so far.

In the event that account info is not found on the dex side the client disables the client account info by prepending ! to the host. This effectively disables the account. After dexc restart the user is prompted to register again. Their password remains the same.

Right now you would have to restart dexc to be prompted with the registration process.

**Comment by kevinstl** [comment]
You can see the work in progress here: https://github.com/kevinstl/dcrdex/tree/unrecognized-account-recovery

**Comment by song50119** [comment]
With multiple DEXs (#404), We might get `already registered at ...`, so I think we have to
check account info is exist from server when `GetFee` or connect again to that dexConnection to make sure it still works

**Comment by JoeGruffins** [comment]
I think it would be ideal that the client receives a receipt from the server after registering that they can later show to prove they have indeed registered. If the server receives such a receipt, that client should be re-added to the database if not there, for whatever reason. I think that would create a buffer for a lot of scenarios we haven't thought of yet.

I'm pretty sure the current registration response has all the info needed to do this. There just needs to be a new endpoint for the server to deal with re-registries.

I don't think forcing the client to pay a fee again with a new account is a good solution.

**Comment by ukane-philemon** [comment]
@chappjc, I don't think this is still an issue, is it?
