### ISSUE TITLE
staking,ui: implement live ui updates for ticket price, stats

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#2497]
As pointed out [here](https://github.com/decred/dcrdex/pull/2482#issuecomment-1695212960), the ticket price does not update as the chain progresses, and we might consider disabling ticket purchasing during initial sync.

Other sync-related tasks to consider are updating of ticket statuses for for tickets in the `ticketPage.history`, and updating of displayed statistics.

**Comment by peterzen** [comment]
Would the following approach be acceptable?
- During initial sync:
  - display the Staking box in a disabled state (if the wallet being used has staking support, otherwise keep it hidden)

- After initial sync:
  - Enable staking box/VSP picker/ticket purchasing
  - Periodically (every 10 mins) call `updateTicketBuyer()` to obtain ticket stats and update staking box

**Comment by buck54321** [comment]
Add the ticket price data to the `(*WalletEmitter).TipChange` notification. Can probably add ticket stats there too.
