### ISSUE TITLE
dex web: wallet config parse error

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#292]
Trying to parse a config file may result in a `could not find option group` error if the config file contains sections other than the default `[Application Options]` section, primarily because the different wallet config structs do not define otherwise supported and valid sections like the [`Ticket Buyer Options` section of dcrwallet config](https://github.com/decred/dcrwallet/blob/f5b98d7c5d089fe5e0ba47bb44bc55aaad3500e8/sample-dcrwallet.conf#L202).

Also; because the current design expects the `Configuration Filepath` field of the create wallet form to point to a location on the dexc web server host machine where a valid wallet config may be found, a user whose wallet daemon runs on a machine different from the web server host machine will need to create a wallet config file on the dexc web server host machine. This is not optimal.

It has been [suggested](https://matrix.to/#/!EzTSRQITaqHuFBDFhM:decred.org/$EseDkIRIQpH94kdervpndPu962z8Y2r2DUaPNi_sNKM?via=decred.org&via=matrix.org&via=planetdecred.org) to implement an `alternate input mode that does not read the config file..., seeing as there are only 2-4 settings anyway` viz `rpcaddress (optional)`, `rpcuser`, `rpcpass` and `rpccert (optional)`.

Doing so would eliminate both potential causes for concern mentioned above.

In order to maintain the ease of specifying wallet settings by parsing a config file, the create wallet form could include a provision to parse wallet connection settings from a file in the user's computer. The file would not need to be uploaded and javascript can be used to parse an ini file to extract the required options while ignoring other options and sections. The extracted settings can be displayed to the user for confirmation before submitting the form.

**Comment by buck54321** [comment]
I would add a few of notes here. 

1. The exact number and type of config fields are asset-specific. [In some previous work](https://github.com/decred/dcrdex/pull/176#discussion_r379444234), I had the `ExchangeWallet` passing out the field names and descriptions as part of the `WalletConfig`, and I still like that idea. That would allow the forms to be generated on the fly. The configuration would be passed to `ExchangeWallet` as a `map[string]string` too. I removed it from that work because I saw the issue as somewhat complicated and wanted a proper solution as a separate PR.

2. I agree that we should allow uploading files via GUI **from the client machine**, like you mention. That's bothered me for a while. You could read the file contents in with javascript, but I'd leave the file parsing up to `Core`. See [here](https://github.com/decred/dcrdex/blob/605ccfaed4a544b11f219eed917bf34e09e94330/client/webserver/site/src/js/register.js#L135-L138) for a similar pattern.

3. All of the settings (the `map[string]string` from 1) will need to be saved to the database. Might even want to encrypt them. This will require a bit of work in the **asset/db** packages.

**Comment by buck54321** [comment]
Seeing as this job is pretty big, we should break it into a few parts.

1. Move file parsing to `Core`. Remove `INIPath string` and add `Settings map[string]string` to `asset.Config` struct. Handle all string parsing internally in `ExchangeWallet` implementations. Ideally, the file could be either INI or a simple JSON mapping, but just INI is okay to start too.

2. Update **db** to store the settings themselves instead of the file path. Maybe encrypt. 

3. File upload.

3. Custom form based on `WalletInfo` as an input option.

**Comment by chappjc** [comment]
All sounds good, especially the custom form based solution.

**Comment by itswisdomagain** [comment]
I want to start on the first part. I'm thinking of moving parsing to `dex` since both client and server require the functionality. Idea actually came to me when examining the current code for parsing the wallets' configs. btc config parsing for wallet (client) and backend (server) use a shared function in `dex/btc/config` because both configs share the same properties of interest.

We could just have one config parsing function in `dex` or `dex/config` that parses an INI or json file and returns `map[string]string`.

**Comment by buck54321** [comment]
**File Parsing** can be moved to **dex**, but if we're only using it in **Core** it's fine there too. 

**`string` parsing** should be handled by the **client/asset/xxx** packages.

It is true that both the client and server share a **config** package, to avoid duplication. I imagine that won't be the case anymore though, since the client and server will now handle configuration much differently. Most of `dex/btc/config` should probably move to `server/asset/btc`.

**Comment by buck54321** [comment]
I realized that **go-flags** may no longer work for our needs, but **gopkg.in/go-ini/ini.v1** would. 

https://play.golang.org/p/DWElOt4f88w

**Comment by itswisdomagain** [comment]
Yeah... I noticed that as well. I was thinking of a custom solution rather than importing another external config file parsing package.

I'd suggest going with `go-ini` only if it can completely replace `go-flags`.

Do you mind having both `go-flags` and `go-ini`? `go-ini` does not support parsing command line args out of the box and that would be a reason to keep `go-flags` (i.ie. if `go-ini` can't be used somehow to parse cli args).

1 possible way of making `go-ini` parse cli args is to convert cli args into an ini string e.g.
the args `--appdata=/user/data --debug=trace` could be easily converted to
```
appdata=/user/data
debug=trace
```
and loaded with `go-ini`'s `ini.Load(...)`.

**Comment by buck54321** [comment]
> Do you mind having both go-flags and go-ini? 

I don't mind at all. I think it's the best option. The **server/cmd/dcrdex** and **client/cmd/dexc** can use `go-flags` to parse into `structs`, and **core** (or **dex**) can use `go-ini` for parsing to `map[string]string`.

I appreciate the efforts to keep the imports under control, but it makes sense to use both here, imo.

**Comment by itswisdomagain** [comment]
Can I get assigned to this issue? I want to implement part 2 next, with part 1 merged.

**Comment by chappjc** [comment]
@itswisdomagain Sounds fine to me.
