### ISSUE TITLE
core: send refund transaction when taker goes dark

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#302]
If 1) the client is the maker on a match, 2) the match status is `MakerSwapCast`, and 3) it's been 48 hours since the swap was broadcast, the maker should `Refund` the swap tx.

**Comment by chappjc** [comment]
Another refund trigger that I alluded to on the DiD discussion is if: (1) the client is the maker (again), (2) the match status is `TakerSwapCast`, and (3) the taker's swap fails audit due to address, amount, locktime, or anything that prevents the maker from redeeming it to the tune of the agreed upon amount.  After the lock time the maker should refund.  The taker presumably is playing games in this case.  I can't recall if client/core already does this... just didn't want to forget this case.

**Comment by itswisdomagain** [comment]
I want to take this up. There's a `wallet.Refund` method to handle refunds but this isn't being triggered yet when a trade goes kaput as described in this issue.

Plan is to implement a tracker (sort of) for trades that failed either because the taker does not send in his counter swap or the counter swap fails audit, then perform auto-refund after the contract locktime expires.

A check for such failed trades would also be done on `dexc` startup to perform auto-refund as necessary.

**Comment by buck54321** [comment]
Consider implementing it as a check in `(*trackedTrade).tick` right alongside the `isRedeemable` and `isSwappable` checks.

**Comment by itswisdomagain** [comment]
A third refund trigger, mentioned in #361, is when
- the client is the **Taker**
- match status is `TakerSwapCast`
- the max allowed time has passed and there's been no redeem info from `Maker`
- it's been 24 hours since the client broadcasted their swap

Actually, once the max allowed time has passed and there's been no redeem info from `Maker`, the client should assume that the `Maker` redeemed their counter swap and begin searching for the redemption tx.
It's possible though that `Maker` actually did not redeem the client's counter swap (prolly didn't get the `audit` request for client's counter swap), in which case the client should issue a refund once the locktime expires.

**Comment by itswisdomagain** [comment]
Another scenario that should trigger a refund is if the client (whether Taker or Maker) has broadcasted their swap but sending the `init` request to the DEX fails:
https://github.com/decred/dcrdex/blob/b55e48c5b936ce6c79fc0e79dbceb149a04bc4b2/client/core/trade.go#L612-L623

I won't be triggering a refund for this scenario yet, I'll add a todo to resend the `init` request before triggering refund.

**Comment by itswisdomagain** [comment]
I'm working on this now.
> Another scenario that should trigger a refund is if the client (whether Taker or Maker) has broadcasted their swap but sending the `init` request to the DEX fails.
