### ISSUE TITLE
client/core: wrong count of fee payment confirmations

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/dcrdex#349]
I have noticed a few wrong behaviors which I think are overlapping into the same bug:

- The thread in the code which watches for changes in the tip of the blockchain fails to trigger the callback when the update of the tip happens too quickly. Which is something unlikely (or impossible?) to happen on testnet/mainnet .On simnet is very easy to verify that by just mining blocks successively while waiting for the fee confirmations.
- What I noticed as more critical than that was that after restarting the dexc, it didn't update the number of confirmations to the correct number, it just kept the staled count I had before.

**Comment by ukane-philemon** [comment]
for issue 2: fee payment confirmation is updated when the client receives the notification of fee payment. Not receiving this notification can be caused by several issues but most prominently due to an unstable connection with the server.

1. Make sure your connection with an online server is strong before commencing fee payment. (this might not apply to localhost servers) 
2. Dexc updates fee status on restart(not recommended).

related #778
 @chappjc what do you think? Dexc does not update fee status when ws connection becomes stable until restart.

**Comment by chappjc** [comment]
The described issues do not seem to be related to dex server connectivity.  The second cause (restarting dexc) is definitely unrelated.  I'm betting that's caused by `reFee` neglecting to send a `c.notify(newFeePaymentNoteWithConfirmations(TopicRegUpdate, ...))` prior to staring `verifyRegistrationFee` to wait for further confs.
