### ISSUE TITLE
client: API Client

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#35]
We need a client to interact with the DEX server. A quick review of the spec indicates that the client would need at least the following functionality.

- Registering a new account
- Maintaining a websocket connection
- Querying for asset info
- Sending orders, progress notifications, etc.
- Syncing orderbook data

The client should be mostly free of `dcrdex` dependencies, but sharing some types via */server/comms/rpc* (#33) is expected.

**Comment by chappjc** [comment]
For reference, here's how we have broken down the DEX client work in the approved Pi proposal:

The DEX client developed in this work will be a command-line interface (CLI) application. However, future development projects will implement a client with a graphical user interface (GUI) using the Electron Framework. The initial client implementation will require a full node (e.g dcrd and btcd) and native wallet software, with which the client will communicate via RPC. The client will comprise the following major components.

* **Connection manager**: Open and close DEX connection. Route messages.
* **Wallet manager**: Query UTXOs. Create, sign, and broadcast transactions.
* **Order book sync**: Download order books and keep them synchronized.
* **User interface**: Registration, charts and tables, order placement, order history.
* **Order manager**: Handle matches. Initialize subsequent atomic swap steps.

The wallet bullet corresponds to dcrdex issues https://github.com/decred/dcrdex/issues/36 and https://github.com/decred/dcrdex/issues/37.
The other bits (excluding the UI) relate to this Issue, although I propose we break up this issue into:
1. DEX connection manager.
2. Order book manager and syncer.
3. Order and swap manager.

**Comment by buck54321** [comment]
Just a couple of notes.

> initialization will be via cli args (which include specifying a config file)

The DEX client should not itself be parsing command line arguments or configuration files. We'll handle that from the main loop. I'd personally prefer just a single `Config` struct as the only argument to the constructor. 

> The websocket connection to the server will be monitored by ping/pong messages exchanged and reconnected if it drops.

The server will ping, you'll just need to pong.

Looks like we're on the right track though. #33 will have some shared json-rpc types, and I've got another branch to push this week with most of the rest.

**Comment by dnldd** [comment]
Regarding sharing types between the server and client. Is the plan to have all message types (request and response) defined in `/server/comms/rpc` ? If not, what is the plan regarding that?

**Comment by buck54321** [comment]
That's what I was thinking.

**Comment by dnldd** [comment]
> That's what I was thinking.

Nice, I think that works well.

**Comment by dnldd** [comment]
This is a draft of details I think the client needs to store. I plan on using bolt db for the client db if there aren't any objections.

```
- the client's private key
- the client version
- archive of all client transactions including swap details keyed by their hashes.
- public key store for known servers keyed by their host addresses.
```

Any other storage details I missed?

**Comment by buck54321** [comment]
This component doesn't require any persistent storage. The DEX client should be mostly limited to the functions described in this issue. Any DB interactions can be implemented as an interface with a stub for testing for now. Doing it that way limits the scope, keeps things modular, and helps to define the storage module when it's time for that work.

**Comment by chappjc** [comment]
Just to reiterate what @buck54321 said in https://github.com/decred/dcrdex/issues/35#issue-499763029, and what I said in https://github.com/decred/dcrdex/issues/35#issuecomment-536579879,
the client process (the executable build output) is not on the table in this issue.  That's in issue https://github.com/decred/dcrdex/issues/38.  Here we are looking at **core client components** that should be isolated from the process concepts of storage, command line flags, etc.

I suggest the first PR pertaining to this issue be focused on **one of the following**, and tested in complete isolation from the higher level bits.

- Account manager.  When separated from other modules like the actual dex comms, this is a micro-component that defines, loads/imports, and creates user identities.  The account's keys and signing functionality can be covered here too.
- Order and swap manager.  There needs to be one or more modules of **"dexclient" (the DEX client product, not the client-server communication bits)** that can (1) generate orders by interfacing with a wallet module (issues #36 and #37) and the account/identity signing module, and (2) create and manage active swaps from orders (in response to notifications from the server although this swap module need not know about the communications module).
- Order book manager and syncer.  The DEX server will provide the order book and incremental updates to the order book.  dexclient must have the order book kept up-to-date so that the user can place orders with this information.  With network communications bits abstracted away, this is also a fairly small module.
- DEX connection manager for communicating with the DEX server (the details of websocket communication) and interfacing with the individual dexclient modules described above for the following activities:
  * Register account with the server.
  * Get dex server and market info (assets, market parameters, order books, etc).
  * Placing and coordinating orders with the server (including swap coordination).
- The wallet modules (#36 and #37 initially)

The actually client-server communications module will probably have to wait though since the DEX server's comms manager isn't merged yet.

**Comment by buck54321** [comment]
My description on this issue is more accurately described as the API client, so I'm updating the title. Let's keep discussion on this issue limited to the component which interacts with the DEX's websocket API.

**Comment by buck54321** [comment]
This issue has evolved and I don't think it is a very good representation of our current direction for development. Many or most of the bullet points from the discussion have been hit anyway. Closing.
