### ISSUE TITLE
client: Decred wallet Client

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#36]
The DEX wallet will need a client to interact with a Decred wallet. This will likely be a wrapper around an [rpcclient](https://github.com/decred/dcrd/tree/master/rpcclient) pointing to a [dcrwallet](https://github.com/decred/dcrwallet).

- Sync UTXO set (`ListUnspent`)
- [Signing UTXO data](https://github.com/buck54321/dcrdex/blob/comms/spec/README.mediawiki#utxo-preparation) (`SignMessage`)
- Signing transaction inputs (`SignRawTransaction`)
- Broadcasting transactions (`SendRawTransaction`)
- Building the swap and redemption transactions

Unlike other wallet clients, the Decred wallet client will also need to create/broadcast DEX registration fee payments. 

Ideally, the wallet will translate between some common type used by the higher-level DEX wallet infrastructure, and the dcrd/rpcclient types. Those common types, and an `interface` for common wallet client functionality can be specified during this work (and with #37). 

This component should be viewed as a plugin component of what could be a simple CLI program or a larger multi-wallet. It is not a stand-alone swap negotiator, so shouldn't be concerned with the negotiation details.

**Comment by dnldd** [comment]
My design of this component (`dcrwclient` would be a good name I think) are as follows: initialization will be done via a configuration struct which will be a subset of the dex client config specific to connecting to the decred wallet. The client will implement a wallet client interface consisting of:
 - ListUnspent
 - SignMesage
 - SignRawTransaction
 - SendRawTransaction 

Considering the sequentially dependent nature of calls related to creating, funding, signing and sending a transaction all query functions will block.

**Comment by chappjc** [comment]
For the last week or so I've been reviewing and testing the dcrwallet CSPP PR (and the corresponding dcrctl PR) because I'm pretty sure we'll need to use the following RPC's too:
* [lockunspent unlock [{"amount":n.nnn,"txid":"value","vout":n,"tree":n},...]](url)
* [listlockunspent](url)

And for proper function, we'll almost certainly want to check wallet config with `walletinfo` and other RPCs:
1. unlocked wallet
2. daemon connected
3. ticket buyer disabled (at least until we are confident that UTXO locking is adequate).
4. adequate versions (of dcrd, dcrdjsonrpcapi, and dcrwalletjsonapi via the `version` RPC).

Some other random thoughts:
* Which account is used for orders?  Any account or must this be specified?  How do we verify the account is capable of performing the necessary functions (not imported xpub, etc.)?
* what happens if a user issues a `rescanwallet` when stuff is locked or an order is on the books or a swap is in progress?  Does that need to be blocked for robustness?
* The auto transaction creator that comes with mixing functionality could very well cause trouble, so we'll need to think through the interactions with the DEX client and the built-in mixing.  e.g. Must disallow placing orders backed by the unmixed account, etc.

**Comment by chappjc** [comment]
Also, I'm concerned about how the auto-lock timeout with `walletpassphrase`.  We may need to find a way to get lock/unlock timeout state from dcrwallet.

**Comment by dnldd** [comment]
> Also, I'm concerned about how the auto-lock timeout with `walletpassphrase`. We may need to find a way to get lock/unlock timeout state from dcrwallet.

https://github.com/decred/dcrwallet/pull/1437 should help with that

**Comment by chappjc** [comment]
As long as that doesn't force use to use gRPC.  If at all possible we only want to use JSON-RPC.

**Comment by dnldd** [comment]
Whoops, missed that important detail.

**Comment by dnldd** [comment]
> Also, I'm concerned about how the auto-lock timeout with `walletpassphrase`. We may need to find a way to get lock/unlock timeout state from dcrwallet.

Could you elaborate on your concern? I think `walletpassphrase` should be adequate for our needs, each call or set of calls will be preceded by `walletpassphrase` unlocking the wallet for a short period of time. The wallet isn't open longer than it needs to be.

**Comment by chappjc** [comment]
I'm referring to how to set the timeout with `walletpassphrase`

    walletpassphrase "passphrase" timeout

What should `timeout` be set to?

> preceded by walletpassphrase (if walletinfo states the wallet is locked) unlocking the wallet for a short period of time

I know the comment is just a thought, but that's another thing to be careful for because it's a race.  `walletinfo` could say unlocked, so we try to do an RPC assuming it is unlocked, but it could very well hit the timeout between these calls.

**Comment by chappjc** [comment]
Still involves a threshold and a race though.

* time remaining is greater than X -> make the call
   - call succeeds if code is fast enough to get it out the door
   - call fails if too slow
* time remaining is less than X -> force an unlock call

**Comment by chappjc** [comment]
So instead of tracking the last timeout, we should just unlock regardless of the current wallet sate.

**Comment by buck54321** [comment]
Resolved by #49 and #92.
