### ISSUE TITLE
websocket: request origin not allowed

### ISSUE THREAD

**Issue by isuldor** [decred/dcrdex#449]
I'm admittedly straying away from the setup instructions by running my dexc setup on a remote machine and using nginx to proxy my connection to the dexc GUI.  That results in this websocket issue:
```
2020-06-05 14:20:43.722 [ERR] WEB: ws connection error: websocket: request origin not allowed by Upgrader.CheckOrigin
2020/06/05 14:20:43 http: superfluous response.WriteHeader call from decred.org/dcrdex/client/webserver.(*WebServer).handleWS (websocket.go:62)
```
My relevant nginx config: https://california.isuldor.com/nginx-conf.txt

Searching for CheckOrigin brought me to this possibly relevant snippet in dcrdata where the origin policy is set to blindly trust by default: https://github.com/decred/dcrdata/blob/a7764026e339b4c98663c1cc4a365f945ff14aff/api/insight/socket.io.go#L94-L99

> Without this affirmative CheckOrigin, gorilla's "sensible default" is to ensure same origin.

My workaround would be to run dexc locally rather than remote (ie. to just follow the dexc testing instructions!).

**Comment by chappjc** [comment]
With dcrdata, there's no authentication, so that's OK.  But with dexc we have to prevent random sites from making your browser (with may have auth tokens) drive secure dexc operations, so a dummy that always returns true won't fly.  But you should be able to directly command a dexc, so this is likely a known issue with gorilla's default check origin function requiring the port to also be the same.  To support your use case I think we will need to rewrite the `checkSameOrigin` function at https://github.com/gorilla/websocket/blob/7e9819d926e9f51e09eabe119b6d78f94e058c44/server.go#L86-L97.  But to figure out exactly why the origin check is failing for you, set the `CheckOrigin` function as follows to see how the Origin header sent by your browser differs from the http.Request.Host value:

```go
websocket.Upgrader{
...
	CheckOrigin: func(r *http.Request) bool {
		origin := r.Header["Origin"]
		fmt.Println(origin[0], r.Host)
		return true
},
...
```

**Comment by chappjc** [comment]
Just looked at your nginx.conf.  You might want to try replacing

```
proxy_set_header Host $host;
```

with 

```
proxy_set_header Host $http_host;
```

as the latter will keep the port as required by the default gorilla checkSameOrigin function.

**Comment by isuldor** [comment]
That cleared the issue and the mistake was on my end afterall.  Thanks!
