### ISSUE TITLE
server/auth: Account penalized upon DEX restart.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#451]
If a client has one order on the books and a DEX server is restarted, that client is penalized with the server message:
`bouncing closed account a186164e417bf59d8c1c4ba6a3e2171465f7a3f00076e926e4c1147be94818ef (cancellation ratio = 1.000000)`

The client shows this error message:
`2020-06-08 14:44:38.697 [ERR] COMMS: No handler found for response: {"type":2,"id":7,"payload":{"result":null,"error":{"code":44,"message":"cancellation ratio (1.000000) exceeds threshold 0.600000"}}}`
Which is odd, as the client, apparently, did not expect a response.

Clients should not be penalized due to the DEX shutting down unexpectedly.

**Comment by chappjc** [comment]
That order must have been canceled, either by the server (revoke) or user.  But this does reveal an issue with market suspend with persist=false because the server-generate order revocations are being counted against the user. `(*AuthManager).loadRecentFinishedOrders` recomputes a user's cancellation ratio on connect, and this needs to distinguish the orders revoked because of persist=false from those canceled by the user or revoked due to inaction or other conduct.

**Comment by JoeGruffins** [comment]
The order was made with tifnow/immediate=false. Is that the same as persist=false?

**Comment by chappjc** [comment]
persist=false is a market suspend option.  If you didn't manually cancel the order, it was either that or the order getting revoked sometime after restart, probably because your client "missed a step".  With some of the swap state PR work, certain requests will be resent, and the client will need changes to field these requests if they are unexpected for the client.

I've assigned this to myself, but it's at least two issues: (1) cancellation ratio affected by order revokes due to no fault of the user, such as market suspend w/o persist (i.e. with an order book purge), and other penalization cases as I alluded to above and (2) the client not understanding the response to the config request (the handler not found error message), which is surprising since this is a client-originating request (`'connect'`).

Even if this wasn't a market suspend with persist=false, the revoked orders that the server generated when purging the books on market stop do need to be distinguished from revocations arising from conduct violations, and I'm addressing that.  I will also look at a number of TODOs to the effect of "do not penalize the user in this edge case".

**Comment by chappjc** [comment]
Oh, if this is your server, please check the server logs for `"checkInaction(failMatch)..."`

**Comment by JoeGruffins** [comment]
I did shut down with `ctrl-c`. I do not see `"checkInaction(failMatch)..."`

**Comment by chappjc** [comment]
Just updated my comment, please also check for the "Flushed..." message on shutdown.

**Comment by JoeGruffins** [comment]
```
2020-06-10 09:07:12.371 [INF] MKT: Flushed 0 sell orders and 0 buy orders from market "dcr_btc" book
2020-06-10 09:07:12.434 [INF] MKT: Market "dcr_btc" stopped.
2020-06-10 09:07:12.435 [INF] DEX: Market[dcr_btc] shutdown.
```

**Comment by JoeGruffins** [comment]
It's easily reproducible for me with the simnet harness.
1. Create account.
2. Register and get confirmed.
3. Make one order.
4. Restart server (with no --anarchy flag)

**Comment by chappjc** [comment]
The order was canceled or revoked before the market shut down... that's interesting.  Still, persist=true should be the default for market shutdown on CTRL+C.  Definitely have debug logs?  Because the only other way besides a user's cancel order to revoke an order is in the `checkInaction` path.

**Comment by chappjc** [comment]
Ah, or failure to respond to a preimage request.  I'd like to figure out if the order was ever booked.

**Comment by chappjc** [comment]
Yet another issue we've talked about is a new server-originating notification route called `'penalty'` or similar so the client gets informed when the server takes any such action.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/495
