### ISSUE TITLE
comms: handle response errors

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#456]
Client responses are sent with the ID of the request, and using `Send`, which doesn't log a handler for a return message. So if the the server encounters an error [in `(*AuthManager).handleResponse`](https://github.com/decred/dcrdex/blob/95d8c3ffd08d6c9c87d7033b25b73a6c14f03027/server/auth/auth.go#L534), or within the response handler, assigning the ID from the client's response to a `msgjson.Error` message doesn't actually make sense. 

How to we best communicate an error for a response?

**Comment by chappjc** [comment]
For a concrete scenario, consider `processInit` making a server-originating `'audit'` request for the counterparty to audit a swap contract that the server just found and verified itself:
- `processInit` makes a request ID for the `'audit'` request, and sends it to the client
- The response handler is `processAck`, where the problem is in this case if there is an error with say the response's json unmarshaling or user signature verification.
- In these cases, `(*Swapper).respondError` sends a *response* to the client, but there was not a client-originating *request*, so this is not appropriate.

A possible solution is to deal with errors in client responses with a *notification*, a new valid message ID from the server (`comms.NextID()`), route of type `'ResponseError'` or similar, and the relevant client response ID that caused the error somewhere in the payload.  The client would need to hang on to their own responses in case there is such a message, which creates more questions like when should these be assumed successful responses and should the server terminate server request -> client response cycles with a minimal OK response...

**Comment by buck54321** [comment]
I'm wondering if a simple solution here might be that some responses get responses of their own. The **client/comms** package would need minimal tweaks to accommodate this scheme. Message ID handling might be a little strange, but it can work, I think.

**Comment by chappjc** [comment]
I suppose I need to refresh my memory, but now I'm wondering why these "responses to responses" don't simply get unmarshalled in a _generic handler_ and if the `Error` field is set, log it.  Such responses are generally just errors that cannot be handled anyway.

The only kind of handling to such errors would be to retry, and that would be the job of the requester to send another request.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?

**Comment by chappjc** [comment]
Maybe.  I think my last comment from a year ago was a reasonable and minimal change (a response without a handler, but with `Error` field set -> log the error as "unhandled response with error msg: X" because there's nothing to do anyway other than **wait for and handle another request that retries the previous failed one**).  Look into it, I suppose.

**Comment by ukane-philemon** [comment]
Alright.
