### ISSUE TITLE
server: dos getfee vulnerability.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#556]
This diff shows how it it is possible for even an unpaid user to completely lock down the DEX for anyone else attempting to connect after this user.

https://github.com/JoeGruffins/dcrdex/commit/d0fb80539fd70451198ec9b8acb12782f1e74765

Now with this dexc you can use the `getfee` route to lock down the server. Note that `rpcMaxClients` has been reduced to 10 for reproduction purposes.

I believe two things need to be changed in order to make this safe.
 - One is to either not give unpaid users a websocket, or limit the time that have to do anything to seconds. Although, the second option may not be enough to stop an attack. Unpaid users could also be given a different max, and a queue could be made.
 - Two is to ensure that the same user cannot create multiple websockets. It should be easier to implement if we go by the rule that one paid user gets one websocket connection. This also should mean not letting the same ip have multiple connections (10+ for nat?) for unpaid users.

**Comment by chappjc** [comment]
It is fairly straightforward to hang up on unauthenticated users after a timeout (e.g. https://github.com/decred/dcrdex/commit/61c35a82c60dcf69c497adb4dfa9a63328bc3bb1), and authenticated users presently are forced to a single websocket connection.  But if we hang up on unauthenticated users, that breaks the idea of a read-only market view mode (https://github.com/decred/dcrdex/issues/142 and https://github.com/decred/dcrdex/issues/726), unless that is an entirely separate websocket server.  And even if we do have the server disconnect unauthenticated users after a certain time, dexc currently just reconnects.

Initially I though that IP limits would make sense, but I think that will cripple clients using it via Tor hidden service since everyone looks like they are coming from localhost.

**Comment by JoeGruffins** [comment]
Would this work.
Limit unauthorized users as suggested above.

Also disconnect comms that are no longer needed for unauthorized users as soon as the server has replied to a request.

For register, this means disconnecting if an error is encountered in the initial registration, or if the fee turns up incorrect in `validateFee`

For client's `getfee` this means changing the connect return parameters for `connect` and making `config` a protected endpoint. If an unpaid client request a connect they are served the config or fee and immediately disconnected, while paid users are connected.

**Comment by JoeGruffins** [comment]
Actually, I guess just limiting the time is the best we can do. A bad actor can tie us up for one minute using the validate fee no matter what we do. Unless we change the validation I think a minute timer for unpaid users is the easy answer.

**Comment by chappjc** [comment]
I'm just not sure how we can make this compatible with https://github.com/decred/dcrdex/issues/556

**Comment by JoeGruffins** [comment]
I that the correct link @chappjc #556 is this issue.

**Comment by chappjc** [comment]
Meant to link to https://github.com/decred/dcrdex/issues/726

**Comment by JoeGruffins** [comment]
I think solved well enough by 5e2ab9153 by limiting connections to the same IP, although still exploitable for someone with lots of resources. I believe we chatted about this somewhere and decided the limiting was good enough. Feel free to re-open if it is still an issue.
