### ISSUE TITLE
server : Subscription Router

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#61]
The **subscription router** will handle requests to the `orderbook` route. The order book updates will probably be sent from the market manager and sent through the **subscription router** to any number of subscribed `comms.Link`s. 

Since the subscription router needs to have some concept of what a market is, it could potentially be part of the `market` package.

**Comment by chappjc** [comment]
> The order book updates will probably be sent from the market manager and sent through the **subscription router** to any number of subscribed `comms.Link`s.

Some ideas about what where subscription router could be:
- a field fo a Market, to which relevant events are sent for forwarding (possibly via router method calls)
- an object (interface or set of channels) registered with the Market, which receives relevant events for forwarding

I imagine a natural design for the orderbook subscription router would involve a single router handling all market subscriptions, with the router shared or registered with each Market (a process that would associate data from the Market with certain dex market subscribers).  Then it would be straightforward for the Market to just hit the router with each order book update.

If done like this, the subs router would only need to understand the concept of an order rather than a market.

**Comment by buck54321** [comment]
I actually ended up doing this one first. Our plans were remarkably similar, @chappjc, but not identical. See what you think about #62.

**Comment by chappjc** [comment]
Yeah, the `BookSource` `interface`, in particular the `OrderFeed` seem great.

I'm fleshing out `market.Market`, so it's good to have this PR up to work around.
