### ISSUE TITLE
client needs to clean-up or auto-cancel unfunded orders on start up

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#614]
If a client shuts down with a booked order, and then the user manually spends the funding coins for those orders, on Core startup it fails:

```
|ERROR| (order) Order coin error - Source coins retrieval error for dcr e51978cb: coins not found: 
c2910530f515d449944caa7ac1d7b75d6e0675cff464b623badc5a778b3489b4:0),                                                                     
|ERROR| (order) Match recovery error - Error auditing counter-parties swap contract during swap 
recovery on order e51978cb: coin not found),
```

But that will happen every time at start up because the order status isn't changed.  Also it would be nice for the client to auto-cancel these orders since the server isn't yet constantly scouring booked orders to ensure their funding coins are unspent.

**Comment by chappjc** [comment]
@itswisdomagain Do you know if we hit this one yet?

**Comment by itswisdomagain** [comment]
Not recently, specifically, not since we stopped unlocking funding coins on shutdown in #648. But it could still happen (if the user were to unlock the coins manually and they end up getting spent). Can keep logging for now but it's a good idea to auto-cancel such orders I think.

Since the server doesn't currently monitor funding coins and revoke orders when their funding coins get spent, can core auto-select a new set of funding coins to ensure that come swap time, the client is ready and able to act? The order may not need to go to hell if we can recover.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdex/pull/981
