### ISSUE TITLE
Add QR codes for deposit addresses

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdex#765]
QR codes make it easier for users who might be transferring from mobile wallets or exchanges.

**Comment by buck54321** [comment]
This one is tricky because we've committed to using no external JS libraries, for security reasons. We could conceivably do it with Go, but I don't know that that's any better. The code would still need to be carefully audited, because sneaking an exploit in would be easy to do and difficult to spot.

Our remaining option is to code up our own QR Code generator or to carefully adapt someone else's into our own codebase.

**Comment by ukane-philemon** [comment]
Closed via #1449
