### ISSUE TITLE
Transaction fee estimates

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdex#823]
When opening an order, it would be nice to get an estimate of how much it would cost the user to execute in transaction fees. This would be determined at the time the trade executes, but an estimate at time of creating the order could still be helpful in many cases, and for market orders I suppose it would be quite accurate.

**Comment by chappjc** [comment]
Related: https://github.com/decred/dcrdex/issues/723

**Comment by chappjc** [comment]
To expand on how I see the issue, it is fundamentally confusing to have `X` in balance, try to place and order that is worth `Y < X`, and having it fail because `Y+fees > X`.  In a number of scenarios, it can be difficult to place an order without iterating order submission.

**Comment by chappjc** [comment]
Related PR that created some of the plumbing for this: https://github.com/decred/dcrdex/pull/842

I think what is needed for the Go API is something like `(*Core).TradeFeeEsimate(base, quote uint32, lots uint64, sell bool) (swap, redeem uint64)`

It would only be an estimate though because the swap fee rate is prescribed by the server, and client's don't have a way to query for the current rate presently.

@buck54321 How do you feel about following up on https://github.com/decred/dcrdex/pull/842 to expose this data.  It has been requested in another context to assist with deciding profitability.

**Comment by buck54321** [comment]
That's what I had  in mind.

**Comment by martonp** [comment]
I'm looking into #859 , and this is a prerequisite. Seems like most if this (except updating the UI) was done by @buck54321 in #958. I can do the UI changes for this so that I can continue with allowing clients to pay higher swap fees.

**Comment by ukane-philemon** [comment]
Closed?
