### ISSUE TITLE
registration page: clicking "show more options" prevents cert registry

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#847]
![image](https://user-images.githubusercontent.com/9373513/99850905-d3bb4200-2b43-11eb-9f70-06481ddb687a.png)

I'm told that "every single last engineer on the face of every planet in the known and unknown universe will click show more options" and I kinda agree.

Problem is that clicking "Show more options" prevents the use of the built-in cert registry.  And you have to F5 the page to get back.  Not intuitive.

**Comment by amassarwi** [comment]
I can try improve that

**Comment by amassarwi** [comment]
@chappjc @buck54321 

I have tried to connect to the testnet dex server after clicking on `show more options` and it still worked as expected, looks like this issue is resolved on master ?

Anyway, I thought we might still improve the ux of the address form by changing `show more options` to `manually upload cert` and maybe add a small cross icon to other state to hide manual upload state ?
