### ISSUE TITLE
Update btc wallet from unencrypted to encrypted

### ISSUE THREAD

**Issue by lukebp** [decred/dcrdex#855]
There's currently no way to update the btc wallet config from an unencrypted wallet to an encrypted wallet.  

When you try to update the wallet name first, you get the following error:
`reconfig error: wallet successfully connected, but errored unlocking. reconfiguration not saved: unlockWallet unlock error: Wallet reporting as locked, but no password has been set`

When you try to update the password first, you get the following error:
`password change error: Error unlocking wallet. Is the new password correct?: rawrequest error: -15: Error: running with an unencrypted wallet, but walletpassphrase was called.`

The gui does not allow you to update both the wallet name and password concurrently.

**Comment by amassarwi** [comment]
I'm trying to repro with a newly created testnet btc wallet: 

Started with unencrypted wallet then encrypted it with `bitcoin-cli` and was able to updates it's password from 
the gui without any issue, lock/unlock works too.

**Comment by buck54321** [comment]
@amassarwi I think the issue is only if you need to change **both** the wallet name **and** the wallet password simultaneously. e.g. connect to an unencrypted wallet, then later want to connect to an encrypted wallet with a different name.

**Comment by amassarwi** [comment]
@buck54321 
oh right!
So moving the password to the same form would be a good way to go here ?

**Comment by buck54321** [comment]
The problem with that approach is that nobody should be forced to change their password to change other settings, and since they would now be required to enter a password into the field, they would effectively forced to change it every time they change a setting. The password field differs from the other fields in that we can't pre-populate it, so the "modify the state and save the changes" approach that is used with the non-password settings can't really apply to the password field.

I think the way to do it might be to start similar to what we have now, but when the user clicks to change the password, the password form just opens as part of the settings form.

<img src="https://user-images.githubusercontent.com/6109680/102807868-1495b900-4385-11eb-810f-e1485c2c2f72.png" width="500">

You of course have to modify the data sent and the handling all the way through `Core` or even `db`, but I think any solution is going to require that anyway.

**Comment by amassarwi** [comment]
@buck54321 Makes sense, will go ahead and implement that.  Thanks )
