### ISSUE TITLE
client/core: async init/redeem requests

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#863]
The second commit in https://github.com/decred/dcrdex/pull/856 (https://github.com/decred/dcrdex/pull/856/commits/0e5c64b9971497b987ce1bfe0da1aa2d3306ba20) is only _touching_ on a mostly-unrelated can of worms.  That is, the init and redeem requests sent by the client are synchronous, blocking in `finalize{Swap,Redeem}Action` while they wait for a response from server.  That needs to change.

Also, this commit addresses an issue with pending requests and reconnects: I realized that when these requests are sent and the server starts a coinwaiter or whatever other processing, and then the connection is lost before getting a response, the `signAndRequest` call will never get a response, just waiting until timeout, which is unfortunately very long (broadcast timeout).  <s>This commit forcibly expires any request handlers on reconnect causing `signAndRequest` to return.</s>  @buck54321 We've waffled on the appropriate timeouts for these requests and I've steered toward just as long as allowable, but given (1) the blocking issue and (2) the fact that core will retry `finalize{Swap,Redeem}Action`, I think the timeouts for `signAndRequest` can be shorter, but I still don't know what the right timeout is.  If we make these things asynchronous, it might be a moot issue though.

Finally, in `finalize{Swap,Redeem}Action`, I think the `match.SetStatus` and update of `proof.{T,M}akerStatus` should be done on broadcast (e.g. in `swapMatchGroup`), esp. since on the first call after bcast you could be sitting at `signAndRequest` without having stored the coin you just broadcasted, plus it's redundant for repeated calls.  The only thing we need to update the match with after `signAndRequest` is `auth.{InitSig,InitStamp}` if we got a response.

_Originally posted by @chappjc in https://github.com/decred/dcrdex/issues/856#issuecomment-736633472_

**Comment by itswisdomagain** [comment]
I want to take this up.

**Comment by itswisdomagain** [comment]
If pending requests aren't forcibly expired on reconnect, then `core` will not retry init/redeem requests until the previous request times out, and if we're using bcastTimeout as request timeout, then there won't be enough time for `core` to resend either request since the server will not accept the new request after `deadline := lastEvent.Add(s.bTimeout)`.

Since we're looking to send the init/redeem requests asynchronously, my first thought is to use a large enough request timeout to allow `core` receive a response from the server. If we're certain we won't be receiving a response (e.g. due to a disconnect), I'd prefer we forcibly expire the previous request to allow core resend a new request.

We could also use a shorter request timeout but that could produce a `SettlementSequenceError` and necessitate a match conflict resolution if a previous request timed out before the server responded.

I'm inclined to go the route of forcibly expiring requests on disconnect/reconnect. I thought this was already done and didn't dig deep there. Is there a reason to not pursue this route?

**Comment by chappjc** [comment]
> I'm inclined to go the route of forcibly expiring requests on disconnect/reconnect. I thought this was already done and didn't dig deep there. Is there a reason to not pursue this route?

In the process of doing https://github.com/decred/dcrdex/pull/856, expire on reconnect was added in https://github.com/decred/dcrdex/pull/856/commits/3925e0af031a6d51b6f1ebd2ae4cd731fcd27330, but then I reverted it because I felt it was only correct to expire the requests if the server had _restarted_ not just a reconnect.  Comment here: https://github.com/decred/dcrdex/pull/856#issuecomment-742563476  Basically I initially thought these requests would never get a response after any kind of reconnect where a new link is made, but the `AuthManager` finds the current connection for the user when sending a reply, so it doesn't matter if the user is on a new connection.

You are absolutely right about the retry being too long if the timeout is bTimeout, which is why in that PR I lowered the timeout to a fraction of bTimeout so that client has time to retry.

I came to the same conclusion about what would happen if the request times out.  That is, if the server responds after the request had timed out, then it would trigger match status resolution.

I don't love all that, but reconnects due to random network stuff happens all the time.  So if we expire the requests on reconnect, that's the right thing to do if the server had restarted (there will never be a response and client should retry), but problematic if it's just a usual reconnect after the connection broke.

**Comment by chappjc** [comment]
A more drastic change to consider: Instead of making init and redeem requests via `conn.Request{WithTimeout}`, we could consider sending these request messages via `conn.Send` and having a special/fallback response handler for when the id does not have a registered handler.  There's not much request-specific handling with these, just unmarshal to a `msgjson.Acknowledgement` and process according to the request type.  Since `msgjson.Acknowledgement` doesn't say what route request it pertains to, only `MatchID`, this could be error prone though as we'd infer which `MatchAuth` field the `Sig` goes to.

**Comment by itswisdomagain** [comment]
> lowered the timeout to a fraction of bTimeout so that client has time to retry

I've maintained this as a temporary fix in #911.

We might want to keep this open or create another issue to better handle cases where the server won't be sending any response, without having to submit up to 4 requests in the broadcast window.

**Comment by chappjc** [comment]
Thanks.  As we discussed in matrix today, if the server tries to respond while the connection is still down the timeout will also be hit.  So in summary:

- reconnect doesn't necessarily prevent a response since AuthManager will send the response on the accounts current link even if it has changed
- restarting the server means no response will ever come
- server responding before client reconnects means no response will ever come

So in my previous comment saying expiring on reconnect is "only the right thing to do if the server had restarted" is not quite right.  I'm now leaning more towards restoring the expire on reconnect that was in https://github.com/decred/dcrdex/commit/3925e0af031a6d51b6f1ebd2ae4cd731fcd27330, but we have to think through what happens if reconnect happens and serer does respond and client does not recognize the response.

**Comment by itswisdomagain** [comment]
Summary of further conversation on matrix:

- long request timeout is a bad idea:
  - primarily because a response might never be received (usually because of a disconnect/reconnect) and waiting too long to error leaves little to no time to retry
   - even if requests are expired on disconnect, a response may never be received for some other unforeseen reason (not a disconnect/reconnect), and we'd be back in the trouble of no time for a retry

- short timeout leaves some room for retry if a response isn't received due to a disconnect/reconnect or any other unforeseen reason

- short timeout + request expiry on disconnect provides even more room for retry in the event of a disconnect
  - instead of waiting the entirety of the timeout to discover that a response isn't received before retrying, expiring the request on disconnect enables an earlier retry (perhaps as soon as or shortly after reconnecting)
  - not allowing the timeout to run to completion could potentially prevent getting a response; a response can still be received after reconnecting if the wait for response isn't immediately interrupted
  - if the server sends a response that is not received because the request is expired due to short timeout or disconnect, a subsequent retry will produce a `SettlementSequenceError` and the correct match state can be recovered

A relatively short timeout of `bTimeout / 4` is currently implemented.

Need to consider all requests not just init/redeem and other gotchas before implementing request expiry on disconnect.
