### ISSUE TITLE
canceling a partially filled order causes revokes

### ISSUE THREAD

**Issue by raedah** [decred/dcrdex#883]
Canceling a partially filled order removes the remaining order from the order book and as well causes any in-progress swaps to go into revoke. Expected behavior when canceling a partially filled order is to remove the remaining order form the order book and to complete the outstanding swaps that have already matched. Forcing a revoke on swap would be a separate action that could be accessed on the order details if needed. Also note that order details doesn't currently display the status of any ongoing revoke. Match revoke status is only shown on the notifications.

**Comment by chappjc** [comment]
Cancelling an order with active swaps does not trigger the match to be revoked.  I'll need more information about what you observed, but matches cannot be interrupted just by cancelling the order.  I suspect there was an unrelated match revoke.

There is no way for a dex user to revoke a swap aside from disconnecting something.  We don't intend to support a way to back out of a swap.

**Comment by raedah** [comment]
perhaps this

[ERR] CORE: cannot redeem order ..., match .., because dcr wallet  is not unlocked

and perhaps the wallet locking is due to not having open orders

**Comment by chappjc** [comment]
That'll do it.  Wallet won't get locked when orders are canceled though.  I do believe it was locked unintentionally somehow.  Any chance you did something with dcrctl?

I would advise getting on the latest dexc release though because [0.1.2 included an automatic wallet (re)unlocking](https://github.com/decred/dcrdex/commit/de409134c37270145dc7094e89d6ef9d8e2d1f74) to avoid revokes that would otherwise occur in such unexpectedly locked wallet situations.  However, you will still need to be logged into dexc for it to be able to unlock wallets automatically like this.

**Comment by raedah** [comment]
Already on 0.1.3. Strange part about it is dcrctl walletinfo is showing the wallet status as unlocked true. dexc output is still showing  not unlocked error occurring.

**Comment by chappjc** [comment]
Hmm, it sounds like it's too late, but you can restart dexc and log back in asap, and it will resume.

**Comment by chappjc** [comment]
@buck54321 This is the locallyUnlocked state error that @raedah cited, while the wallet itself appears unlocked according to dcrctl walletinfo.  What circumstances do you think this can get out of agreement?  I feel like we've seen some similar disagreement as a result of killing dexc, but it's not clear exactly how that could happen.

**Comment by raedah** [comment]
restarting dexc results in these msgs

[DBG] CORE: AuditContract error for match ... status TakerSwapCast, refunded = false, revoked = true: coin not found
[ERR] CORE: notify: |ERROR| (order) Match recovery error - Error auditing counter-party's swap contract (...) during swap recovery on order ... :0: coin not found - Order: ...

[WRN] CORE: DEX dex.decred.org:7232 did not report active match .... on order ... - assuming revoked.

[TRC] CORE: Not finding redemption for match ...: side = Maker, swapErr = audit error, order ..., match ...: coin not found, TakerSwap = ... RefundCoin =

**Comment by chappjc** [comment]
Since the match is revoked and needs to go the refund route, that audit error is OK, but out of curiosity, was the counterparty swap contract txn it is looking for in the ERR message mined at the time of that check?

The TRC message "Not finding redemption" is normal when you are Maker. (only taker needs to watch for an unannounced redeem of maker's contract).

But I believe there is an issue with reconfiguring wallet (changing wallet setting) while there are active swaps, so please avoid that until we resolve the issue.

**Comment by raedah** [comment]
It appears that the refund did occur after the dexc restart.
