### ISSUE TITLE
Inconsistent git tag names

### ISSUE THREAD

**Issue by xaur** [decred/dcrdex#936]
```
v0.1.4
v0.1.3
v0.1.2
v0.1.1
release-v0.1.1
v0.1.1-beta1
release-v0.1.0
```

**Comment by chappjc** [comment]
The first ones with release were made with a different module structure.  The creation of the "beta1" tag is also a little unfortunate because now all go consumer will latch onto that as the latest as it's semver compatible for modules

I'm planning to stick with the later semver tags unless and until the module version differs from theb product release version.  Otherwise I'd have to make two tags at the exact same commit. e.g. `v0.1.4` (for the go module) and `release-v0.1.4` (to be consistent with the other repo releases).

In your mind b@xaur, what specifically should change? I can't delete the old tags.

**Comment by chappjc** [comment]
I noticed dcrwallet is creating multiple tags at the same commit, presumably for a similar reason (one semver compatible and one with the release- prefix).  I had no intention of continuing the `release-` tags, but if there's a good reason, I will make them.

**Comment by xaur** [comment]
I discovered this by going through [GitHub releases](https://github.com/decred/dcrdex/releases) and thought I'd report it just in case.

To have it pretty from GitHub release perspective I would create `v0.1.0` tag at same commit as `release-v0.1.0`, and move two first GitHub releases from `release-` tags to `v0.1.x` tags. This way I could go through `https://github.com/decred/dcrdex/releases/tag/{version}` (possibly via GitHub API) with a consistent iteration. But I would only bother with it if moving GH release doesn't cause significant pita.

Else I would just add one `v0.1.0` tag and as you say, continue without `release-` tags until there is a good reason to make them.

**Comment by chappjc** [comment]
Makes sense.  I can adjust the GitHub release tags like that.

**Comment by chappjc** [comment]
Will be consistent going forward.  The ship has sailed on old releases.
