### ISSUE TITLE
ui: markets view order book tables should bin by rate

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#945]
It has been noticed that different orders with the same rate have separate rows in the "Buy Orders" and "Sell Orders" tables. 
![image](https://user-images.githubusercontent.com/6109680/106054827-2cfaa100-60b2-11eb-8bf2-caa8c6248378.png)
While that's technically correct because we're listing "orders", it's also bad UX. Instead, the table rows should bin orders by rate, displaying the combined quantity. 

This is pretty standard practice in market views, and many data API "order books" actually provide pseudo-orders that represent the rate bin. I don't recommend we do that, though. We can do the binning right where we create the row elements in markets.js.

**Comment by martonp** [comment]
I'll work on this.

**Comment by chappjc** [comment]
In addition to the bins, the Buy/Sell Orders tables need to be limited in height with vscroll of their own.  Otherwise the Your Orders tables that goes below them in narrower windows leaves the visible part of the screen.

**Comment by martonp** [comment]
Another issue: if you place limit order with immediate execution, and you pick a price that does not get executed, it shows in the "Your orders" section as executed. This is just a UI issue. If the page is refreshed this order disappears.

**Comment by chappjc** [comment]
I think that "executed" thing is a persistent source of confusion, but it's not really incorrect.  It did not match, but since it was not standing, it didn't get booked.  But the order's status isn't cancelled either.  Basically we consider an order executed if it is simply finished matching and no longer booked.  This includes 0% filled.  I'm open to another adjective to describe such 0% fill orders on the UI though.

**Comment by martonp** [comment]
"expired"?
