### ISSUE TITLE
UI: on Withdraw page, show current fee rate estimate

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#970]
Since bitcoind's fee rate estimation can be wildly inaccurate if bitcoind has just started and hasn't had a chance to really warm up (the gray area where estimatesmartfee does not throw an error but instead returns poor estimates), the withdraw page could show the backend's current fee rate estimate to help the user decide if it's going to be be appropriate given external sources such as mempool.space.

**Comment by amassarwi** [comment]
will do next

**Comment by amassarwi** [comment]
Discussing a proper approach for this issue with @chappjc on matrix, here are some thoughts towards a possible solution:

1. To get the estimated fee to the UI; `Core` would need to fetch that from assets' backend using some exported func
(ie `FeeRate`),  one issue with relying purely on that would be `SPV` wallets which won't return any value, @chappjc suggested to fallback to [Core.feeSuggestion](https://github.com/decred/dcrdex/blob/a1fbdc023c/client/core/core.go#L2934) which tries to get a fee using a synced order book and if no value available it asks the server.

2. UI would display the value suggested above in a kind of form to give the user an option (ie checkbox) to use manual fee rate. This would give the user full control and the right to decide which fee rate is sensible and which isn't when withdrawing funds. 
Withdraw is the one place where entering their own fee rate makes sense.  This is because it is a single txn made right then, unlike swaps or redeems that happen at time X that cannot be predicted.  Plus with redeems it's very dangerous to use a fee that is too low because if a maker's redeem isn't mined in time.

3. 1 & 2 suggest that a fee rate should be passed to `Withdraw`, as explained above UI will always pass a non-zero value
as the user will either agree on the suggested fee rate or specify his own rate, but in case of Go consumers the fee rate
passed value can be zero.

@buck54321 What do think about the drafted flow? does it make sense to you?

**Comment by chappjc** [comment]
That all summarizes it, except we did consider `WalletState` as a home for the current fee rate estimate, but those notes are generally purposed for connection/lock state updates rather than balance, although Balance is a part of WalletState.  But given the current notification system, and the use of balance on the Withdraw page, it does feel like Balance and BalanceNote would be appropriate.

**Comment by chappjc** [comment]
Will be resolvable by https://github.com/decred/dcrdex/pull/1430 and/or https://github.com/decred/dcrdex/pull/1419

**Comment by buck54321** [comment]
> @buck54321 What do think about the drafted flow? does it make sense to you?

Woah. Sorry I missed this @amass. I don't know what I was doing last April, but I obviously wasn't working.

**Comment by ukane-philemon** [comment]
Resovled by #1430 and #1444.

**Comment by amass01** [comment]
@ukane-philemon nope

**Comment by ukane-philemon** [comment]
@chappjc , closed? https://github.com/decred/dcrdex/pull/1688

**Comment by chappjc** [comment]
fee != fee rate

I think what's really missing from the frontend is the ability to specify the fee rate you want to use.  Virtually all wallets let you do this.

**Comment by ukane-philemon** [comment]
> I think what's really missing from the frontend is the ability to specify the fee rate you want to use. Virtually all wallets let you do this.

Okay, since this issue was about `show current fee rate estimate`, I concluded it has been resolved. However, having a `slow`, `medium`, `fast` and a `custom` option for a user to specify their preferred tx fee rate is worth it.

**Comment by ukane-philemon** [comment]
I would like to work on this https://github.com/decred/dcrdex/issues/970#issuecomment-1280056763, any other thoughts?
